### ISSUE TITLE
Branch push access rights

### ISSUE THREAD

**Issue by kameel2311** [DoongLi/awesome-Implicit-NeRF-SLAM#34]
I have created local branch for Nerf Reloc to add new papers to create a pull request but I dont have access to push my local branch

**Comment by DoongLi** [comment]
Why, I think anyone who all allows pr.

**Comment by DoongLi** [comment]
I think you should fork this repo fristly.

**Comment by DoongLi** [comment]
I close the comment, and if you have any questions, you can continue to leave a message below or send an email to me.
