### ISSUE TITLE
Find a wrong classification.

### ISSUE THREAD

**Issue by jiang-junlong** [DoongLi/awesome-Implicit-NeRF-SLAM#36]
Neural Surface Reconstruction and Rendering for LiDAR-Visual Systems, arXiv, 2024. is neural implicit SLAM.

**Comment by DoongLi** [comment]
Thank you for the reminder! It seems I did indeed cause a wrong classification. I will fix this issue tomorrow.

**Comment by DoongLi** [comment]
I have fixed this type error, thx again~
